In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
result_directory = '/content/drive/MyDrive/NLP Projects/Sentiment analysis/results/'

In [9]:
import torch
from transformers import AutoModelForSequenceClassification, BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

model = AutoModelForSequenceClassification.from_pretrained(result_directory)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def predict(input_text):
  inputs = tokenizer(input_text, return_tensors="pt").to(device)

  # انجام پیش‌بینی
  with torch.no_grad():
      outputs = model(**inputs)
      logits = outputs.logits
      predictions = torch.argmax(logits, dim=-1)

  return predictions

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Positive Texts

In [10]:
predict("This movie was amazing! I really enjoyed watching it.")

tensor([1])

In [11]:
predict("The products from this brand are of very high quality, and I'm always satisfied with them.")

tensor([1])

In [12]:
predict("The customer service at this store is outstanding. I always feel good when I go there.")

tensor([1])

Negative Texts

In [13]:
predict("This book was very boring, and I couldn't finish it.")

tensor([0])

In [14]:
predict("The quality of this product is very low, and I regret my purchase.")

tensor([0])

In [15]:
predict("My experience at this restaurant was not good at all. The food was cold and tasteless.")

tensor([0])